# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

replace_na_false <- function(x) {
    invisible(.Call(`_datatools_replace_na_false`, x))
}

int_remove_na <- function(x) {
    .Call(`_datatools_int_remove_na`, x)
}

is_true_or_false <- function(x) {
    .Call(`_datatools_is_true_or_false`, x)
}

is_string <- function(x) {
    .Call(`_datatools_is_string`, x)
}

